### ISSUE TITLE
it seemed not support redmine2.1.2

### ISSUE THREAD

**Issue by archonwang** [tdvsdv/unread_issues#4]
I tested it on Redmine 2.1.2.  Unfornately, it could not support the version ver well, when I opened the plugins/unread_issues/configuration page.

the error information is here, please check it or give some advice about the issues. Thanks so much.
# 

Started GET "/settings/plugin/unread_issues" for 192.168.3.41 at 2012-11-14 13:30:20 +0800
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"unread_issues"}
  Current user: archonwang(id=39)
  Rendered plugins/unread_issues/app/views/settings/_unread_issues_settings.html.erb (1.4ms)
  Rendered settings/plugin.html.erb within layouts/admin (2.4ms)
Completed 500 Internal Server Error in 7ms

ActionView::Template::Error (undefined method `settings' for nil:NilClass):
    1: <%- defaults = Redmine::Plugin::registered_plugins[:advanced_roadmap].settings[:default] -%>
    2: <% frequency=@settings['frequency'].to_i || defaults['frequency'].to_i%>
    3: <% decay=@settings['decay'].to_i || defaults['decay'].to_i%>
    4: 
  app/views/settings/plugin.html.erb:6:in`block in _c89eb32e0722acf987236154ba8809f1'
  app/views/settings/plugin.html.erb:4:in `_c89eb32e0722acf987236154ba8809f1'

**Comment by dkuk** [comment]
Looks like API of plugin registration changed in RM 2.1

I think, if defaults will be removed from settings, plugin will work, except of periodical updater of unread issues counters in top menu. The root of the periodical update problem is prototype.js which used as base engine in redmine older than 2.1

We are planing migration to RM 2.1+, as soon as possible, but can't say when

**Comment by archonwang** [comment]
Hi, @dkuk 

I see. 

I used redmine advanced_roadmap v0.8.0 and migrate unread_issues again, and it works well on RM2.1.2

I think  if you could write some wiki page or instruction, it will be more confident.  

Thanks.

**Comment by tdvsdv** [comment]
I'm glad that our plugin is usefull for you

**Comment by dkuk** [comment]
I'll try to do this a little bit later. There are no any time for this.
You may try also https://github.com/dkuk/advanced_roadmap which is more powerful and fast (i hope).
It provides of auto-planning issues dates for users, upgrades Issues with executor field, show stats, introduces milestones (which is a group of versions) to Redmine
Also it splits version and milestone issues by tabs (grouped by executors). It makes planning and controling process faster an situatable for departments managers

**Comment by cforce** [comment]
saem bug here.. Why is that other plugin in treat here?
